server:
  port: 80
  servlet:
    context-path: /studyNote
# «˝∂Ø≈‰÷√–≈œ¢
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study_note?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
